version: "3.3"

services:
  dsjobapp:
    # かめさんが用意した環境を利用
    # image: "datascientistus/ds-python-env3"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8888"
    volumes:
      - ./work:/work
    working_dir: /work
