version: "3.3"

services:
  dsjobapp:
    build:
      context: .
      dockerfile: Dockerfile
    # イメージ名を指定
    image: math-ml-env
    ports:
      - "8889:8888"
    volumes:
      - ./work:/work
    working_dir: /work
